apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  selector:
    {{- include "wordpress.labels" . | nindent 4 }}
    tier: mysql
