apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.keyVaultName }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.secretProviderClass.clientID | quote }}
    keyvaultName: sigma-devops-test
    objects: |
      array:
        - |
          objectName: mysql-pass
          objectType: secret
    tenantId: {{ .Values.secretProviderClass.tenantId | quote }}
  secretObjects:
  - data:
    - key: password
      objectName: mysql-pass
    secretName: mysql-pass
    type: Opaque
