apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonly-cluster
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: readonly-cluster
subjects:
- kind: User
  # az ad signed-in-user show --query id -o tsv
  name: "d314ddc1-22b7-4414-92fe-04a457f8b1bb"
  apiGroup: rbac.authorization.k8s.io
