apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-user
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readonly-user
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-user
subjects:
- kind: ServiceAccount
  name: readonly-user
roleRef:
  kind: Role
  name: readonly-user
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: readonly-user
  annotations:
    kubernetes.io/service-account.name: readonly-user
type: kubernetes.io/service-account-token
